python run_oe_clevrer.py \
    --program_path /home/zfchen/code/clevrer_dataset_generation_v2/clevrer_question_generation/output/questions_v16_3_2/open_end_questions.json \
    --question_path /home/zfchen/code/clevrer_dataset_generation_v2/clevrer_question_generation/output/questions_v16_3_2/open_end_questions.json \
    --raw_motion_prediction_dir /home/zfchen/code/output/render_output_vislab3/v16/predictions_gt_v2 \
    --ann_dir /home/zfchen/code/output/render_output_vislab3/v16/render/causal_sim \
    --gt_flag 1 \
    --num_sim 10000 \
    --start_id 0 \
    --ann_offset 0 \
    --use_event_ann 1 \
    --gen_ambi_flag 1 \
    --ambi_ques_list_fn ./data/ambi_ques_v16_3_2.txt \
    --invalid_video_fn ./data/invalid_video_v16_3_2.txt \
    #--ann_dir /home/zfchen/code/output/ns-vqa_output/v11_prp_refine/config \
