python run_oe_clevrer.py \
    --program_path /home/zfchen/code/clevrer_dataset_generation_v2/clevrer_question_generation/output/questions_v16_2_test/open_end_questions.json \
    --question_path /home/zfchen/code/clevrer_dataset_generation_v2/clevrer_question_generation/output/questions_v16_2_test/open_end_questions.json \
    --raw_motion_prediction_dir /home/zfchen/code/output/render_output_vislab3/v16_test/predictions_motion_gt_v1 \
    --ann_dir /home/zfchen/code/output/render_output_vislab3/v16_test/render/causal_sim \
    --gt_ann_dir /home/zfchen/code/output/render_output_vislab3/v16_test/render \
    --gt_flag 1 \
    --num_sim 2000 \
    --start_id 10000 \
    --ann_offset 10000 \
    --use_event_ann 1 \
    --gen_ambi_flag 1 \
    --ambi_ques_list_fn ./data/ambi_ques_v16_1_test.txt \
    --invalid_video_fn ./data/invalid_video_v16_1_test.txt \
    #--ann_dir /home/zfchen/code/output/ns-vqa_output/v11_prp_refine/config \
