python run_mc_clevrer.py \
    --gt_flag 0 \
    --use_event_ann 0 \
    --n_progs 1000 \
    --ann_dir /home/zfchen/code/output/render_output/causal_sim_v11_4 \
    --program_path /home/zfchen/code/clevrer_dataset_generation_v2/clevrer_question_generation/output/questions_v11/multiple_choice_questions.json \
    --question_path /home/zfchen/code/clevrer_dataset_generation_v2/clevrer_question_generation/output/questions_v11/multiple_choice_questions.json \
    --raw_motion_prediction_dir /home/zfchen/code/output/render_output_disk2/prediction_v11_prp \
    --ann_dir /home/zfchen/code/output/ns-vqa_output/v11_prp_pred/config \
    --invalid_video_fn '' \
